// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type _404DocumentDataSlicesSlice = never;

/**
 * Content for 404 documents
 */
interface _404DocumentData {
  /**
   * Image Desktop field in *404*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: 404.image_desktop
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_desktop: prismic.ImageField<never>;

  /**
   * Image Mobile field in *404*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: 404.image_mobile
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_mobile: prismic.ImageField<never>;

  /**
   * message field in *404*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. It looks like the page you’re looking for has wandered off.
   * - **API ID Path**: 404.message
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  message: prismic.KeyTextField;

  /**
   * Slice Zone field in *404*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: 404.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<_404DocumentDataSlicesSlice> /**
   * Meta Title field in *404*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: 404.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *404*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: 404.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *404*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: 404.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * 404 document from Prismic
 *
 * - **API ID**: `404`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type _404Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<_404DocumentData>, "404", Lang>;

type AboutDocumentDataSlicesSlice = AboutTextSlice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice> /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Links field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Links field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.links
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Mail field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.mail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  mail: prismic.KeyTextField;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomepageDocumentDataSlicesSlice = CardProjectSlice | DiptychImagesSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type IndexPageDocumentDataSlicesSlice = ProjectGroupSlice;

/**
 * Content for Index page documents
 */
interface IndexPageDocumentData {
  /**
   * Slice Zone field in *Index page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: index_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<IndexPageDocumentDataSlicesSlice> /**
   * Meta Title field in *Index page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: index_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Index page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: index_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Index page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: index_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Index page document from Prismic
 *
 * - **API ID**: `index_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IndexPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<IndexPageDocumentData>,
    "index_page",
    Lang
  >;

type LegalsDocumentDataSlicesSlice = AboutTextSlice;

/**
 * Content for Legals documents
 */
interface LegalsDocumentData {
  /**
   * Slice Zone field in *Legals*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: legals.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LegalsDocumentDataSlicesSlice> /**
   * Meta Title field in *Legals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: legals.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Legals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: legals.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Legals*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: legals.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Legals document from Prismic
 *
 * - **API ID**: `legals`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LegalsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LegalsDocumentData>,
    "legals",
    Lang
  >;

type PortfolioDocumentDataSlicesSlice = CardProjectSlice | DiptychImagesSlice;

/**
 * Content for Portfolio documents
 */
interface PortfolioDocumentData {
  /**
   * Slice Zone field in *Portfolio*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PortfolioDocumentDataSlicesSlice> /**
   * Meta Title field in *Portfolio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: portfolio.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Portfolio*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: portfolio.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Portfolio*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: portfolio.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Portfolio document from Prismic
 *
 * - **API ID**: `portfolio`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PortfolioDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PortfolioDocumentData>,
    "portfolio",
    Lang
  >;

type ProjectDocumentDataSlicesSlice = VariationsImagesSlice | AboutProjectSlice;

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Image Desktop field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.image_desktop
   * - **Tab**: Card Project
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_desktop: prismic.ImageField<never>;

  /**
   * Image Mobile field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.image_mobile
   * - **Tab**: Card Project
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_mobile: prismic.ImageField<never>;

  /**
   * Vimeo Link field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. 1125178794
   * - **API ID Path**: project.vimeo_link
   * - **Tab**: Card Project
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  vimeo_link: prismic.KeyTextField;

  /**
   * Vimeo Link Mobile field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. 1125178794
   * - **API ID Path**: project.vimeo_link_mobile
   * - **Tab**: Card Project
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  vimeo_link_mobile: prismic.KeyTextField;

  /**
   * Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Mugler
   * - **API ID Path**: project.title
   * - **Tab**: Card Project
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField /**
   * Slice Zone field in *Project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices[]
   * - **Tab**: Content Project
   * - **Documentation**: https://prismic.io/docs/slices
   */;
  slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice> /**
   * Meta Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: project.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: project.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

export type AllDocumentTypes =
  | _404Document
  | AboutDocument
  | FooterDocument
  | HeaderDocument
  | HomepageDocument
  | IndexPageDocument
  | LegalsDocument
  | PortfolioDocument
  | ProjectDocument;

/**
 * Primary content in *AboutProject → Default → Primary*
 */
export interface AboutProjectSliceDefaultPrimary {
  /**
   * Description field in *AboutProject → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: e.g. Mugler project is a project about...
   * - **API ID Path**: about_project.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Details field in *AboutProject → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Client's name
   * - **API ID Path**: about_project.default.primary.details
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  details: prismic.KeyTextField;

  /**
   * Year field in *AboutProject → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. 2025
   * - **API ID Path**: about_project.default.primary.year
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  year: prismic.KeyTextField;
}

/**
 * Default variation for AboutProject Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutProjectSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutProjectSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutProject*
 */
type AboutProjectSliceVariation = AboutProjectSliceDefault;

/**
 * AboutProject Shared Slice
 *
 * - **API ID**: `about_project`
 * - **Description**: AboutProject
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutProjectSlice = prismic.SharedSlice<
  "about_project",
  AboutProjectSliceVariation
>;

/**
 * Primary content in *AboutText → Default → Primary*
 */
export interface AboutTextSliceDefaultPrimary {
  /**
   * Title field in *AboutText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. About
   * - **API ID Path**: about_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *AboutText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: e.g. Julien Vallon is a French visual artist...
   * - **API ID Path**: about_text.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for AboutText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutText*
 */
type AboutTextSliceVariation = AboutTextSliceDefault;

/**
 * AboutText Shared Slice
 *
 * - **API ID**: `about_text`
 * - **Description**: AboutText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutTextSlice = prismic.SharedSlice<
  "about_text",
  AboutTextSliceVariation
>;

/**
 * Primary content in *ProjectCard → Default → Primary*
 */
export interface CardProjectSliceDefaultPrimary {
  /**
   * Project field in *ProjectCard → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: card_project.default.primary.project
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  project: ContentRelationshipFieldWithData<
    [
      {
        id: "project";
        fields: [
          "image_desktop",
          "image_mobile",
          "vimeo_link",
          "vimeo_link_mobile",
          "title",
          "category",
        ];
      },
    ]
  >;

  /**
   * Size field in *ProjectCard → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Full Width
   * - **API ID Path**: card_project.default.primary.size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  size: prismic.SelectField<"Full Width" | "XL" | "L" | "M" | "S", "filled">;

  /**
   * Position field in *ProjectCard → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: card_project.default.primary.position
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  position: prismic.SelectField<"Left" | "Center" | "Right", "filled">;
}

/**
 * Default variation for ProjectCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CardProjectSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardProjectSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectCard*
 */
type CardProjectSliceVariation = CardProjectSliceDefault;

/**
 * ProjectCard Shared Slice
 *
 * - **API ID**: `card_project`
 * - **Description**: CardProject
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CardProjectSlice = prismic.SharedSlice<
  "card_project",
  CardProjectSliceVariation
>;

/**
 * Item in *DiptychProjectCard → Default → Primary → Side Left*
 */
export interface DiptychImagesSliceDefaultPrimarySideLeftItem {
  /**
   * Project field in *DiptychProjectCard → Default → Primary → Side Left*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: diptych_images.default.primary.side_left[].project
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  project: ContentRelationshipFieldWithData<
    [
      {
        id: "project";
        fields: [
          "vimeo_link",
          "vimeo_link_mobile",
          "title",
          "category",
          "image_desktop",
          "image_mobile",
        ];
      },
    ]
  >;

  /**
   * Size field in *DiptychProjectCard → Default → Primary → Side Left*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: S
   * - **API ID Path**: diptych_images.default.primary.side_left[].size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  size: prismic.SelectField<"S" | "M", "filled">;

  /**
   * Vertical Position field in *DiptychProjectCard → Default → Primary → Side Left*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: diptych_images.default.primary.side_left[].vertical_position
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  vertical_position: prismic.SelectField<"Left" | "Center" | "Right", "filled">;

  /**
   * Horizontal Position  field in *DiptychProjectCard → Default → Primary → Side Left*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Top
   * - **API ID Path**: diptych_images.default.primary.side_left[].horizontal_position
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  horizontal_position: prismic.SelectField<
    "Top" | "Center" | "Bottom",
    "filled"
  >;
}

/**
 * Item in *DiptychProjectCard → Default → Primary → Side Right*
 */
export interface DiptychImagesSliceDefaultPrimarySideRightItem {
  /**
   *  Project field in *DiptychProjectCard → Default → Primary → Side Right*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: diptych_images.default.primary.side_right[].project
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  project: ContentRelationshipFieldWithData<
    [
      {
        id: "project";
        fields: [
          "image_desktop",
          "vimeo_link",
          "vimeo_link_mobile",
          "image_mobile",
          "title",
          "category",
        ];
      },
    ]
  >;

  /**
   * Size field in *DiptychProjectCard → Default → Primary → Side Right*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: S
   * - **API ID Path**: diptych_images.default.primary.side_right[].size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  size: prismic.SelectField<"S" | "M", "filled">;

  /**
   * Vertical Position field in *DiptychProjectCard → Default → Primary → Side Right*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: diptych_images.default.primary.side_right[].vertical_position
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  vertical_position: prismic.SelectField<"Left" | "Center" | "Right", "filled">;

  /**
   * Horizontal Position  field in *DiptychProjectCard → Default → Primary → Side Right*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Top
   * - **API ID Path**: diptych_images.default.primary.side_right[].horizontal_position
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  horizontal_position: prismic.SelectField<
    "Top" | "Center" | "Bottom",
    "filled"
  >;
}

/**
 * Primary content in *DiptychProjectCard → Default → Primary*
 */
export interface DiptychImagesSliceDefaultPrimary {
  /**
   * Side Left field in *DiptychProjectCard → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: diptych_images.default.primary.side_left[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  side_left: prismic.GroupField<
    Simplify<DiptychImagesSliceDefaultPrimarySideLeftItem>
  >;

  /**
   * Side Right field in *DiptychProjectCard → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: diptych_images.default.primary.side_right[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  side_right: prismic.GroupField<
    Simplify<DiptychImagesSliceDefaultPrimarySideRightItem>
  >;
}

/**
 * Default variation for DiptychProjectCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DiptychImagesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DiptychImagesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DiptychProjectCard*
 */
type DiptychImagesSliceVariation = DiptychImagesSliceDefault;

/**
 * DiptychProjectCard Shared Slice
 *
 * - **API ID**: `diptych_images`
 * - **Description**: DyptchImages
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DiptychImagesSlice = prismic.SharedSlice<
  "diptych_images",
  DiptychImagesSliceVariation
>;

/**
 * Item in *ProjectGroup → Default → Primary → Projects*
 */
export interface ProjectGroupSliceDefaultPrimaryProjectsItem {
  /**
   * Project field in *ProjectGroup → Default → Primary → Projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project_group.default.primary.projects[].project
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  project: ContentRelationshipFieldWithData<
    [
      {
        id: "project";
        fields: [
          "image_desktop",
          "image_mobile",
          "vimeo_link",
          "vimeo_link_mobile",
          "title",
        ];
      },
    ]
  >;
}

/**
 * Primary content in *ProjectGroup → Default → Primary*
 */
export interface ProjectGroupSliceDefaultPrimary {
  /**
   * Projects field in *ProjectGroup → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project_group.default.primary.projects[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  projects: prismic.GroupField<
    Simplify<ProjectGroupSliceDefaultPrimaryProjectsItem>
  >;
}

/**
 * Default variation for ProjectGroup Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectGroupSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectGroupSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectGroup*
 */
type ProjectGroupSliceVariation = ProjectGroupSliceDefault;

/**
 * ProjectGroup Shared Slice
 *
 * - **API ID**: `project_group`
 * - **Description**: ProjectGroup
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectGroupSlice = prismic.SharedSlice<
  "project_group",
  ProjectGroupSliceVariation
>;

/**
 * Primary content in *SingleMedia → Media Only → Primary*
 */
export interface VariationsImagesSliceDefaultPrimary {
  /**
   * Image Desktop field in *SingleMedia → Media Only → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: variations_images.default.primary.image_desktop
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_desktop: prismic.ImageField<never>;

  /**
   * Image Mobile field in *SingleMedia → Media Only → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: variations_images.default.primary.image_mobile
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_mobile: prismic.ImageField<never>;

  /**
   * Vimeo Link field in *SingleMedia → Media Only → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. 1125178794
   * - **API ID Path**: variations_images.default.primary.vimeo_link
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  vimeo_link: prismic.KeyTextField;

  /**
   * Vimeo Link Mobile field in *SingleMedia → Media Only → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. 1125178794
   * - **API ID Path**: variations_images.default.primary.vimeo_link_mobile
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  vimeo_link_mobile: prismic.KeyTextField;

  /**
   * Link Film field in *SingleMedia → Media Only → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: variations_images.default.primary.link_film
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  link_film: prismic.EmbedField;

  /**
   * Link Film Mobile field in *SingleMedia → Media Only → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: variations_images.default.primary.link_film_mobile
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  link_film_mobile: prismic.EmbedField;

  /**
   * Full width field in *SingleMedia → Media Only → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: variations_images.default.primary.full_width
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  full_width: prismic.BooleanField;

  /**
   * Position field in *SingleMedia → Media Only → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: variations_images.default.primary.position
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  position: prismic.SelectField<"Left" | "Center" | "Right", "filled">;

  /**
   * Background Color field in *SingleMedia → Media Only → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: #222222
   * - **API ID Path**: variations_images.default.primary.bg_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  bg_color: prismic.ColorField;
}

/**
 * Media Only variation for SingleMedia Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VariationsImagesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VariationsImagesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SingleMedia*
 */
type VariationsImagesSliceVariation = VariationsImagesSliceDefault;

/**
 * SingleMedia Shared Slice
 *
 * - **API ID**: `variations_images`
 * - **Description**: VariationsImages
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VariationsImagesSlice = prismic.SharedSlice<
  "variations_images",
  VariationsImagesSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      _404Document,
      _404DocumentData,
      _404DocumentDataSlicesSlice,
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      HeaderDocument,
      HeaderDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      IndexPageDocument,
      IndexPageDocumentData,
      IndexPageDocumentDataSlicesSlice,
      LegalsDocument,
      LegalsDocumentData,
      LegalsDocumentDataSlicesSlice,
      PortfolioDocument,
      PortfolioDocumentData,
      PortfolioDocumentDataSlicesSlice,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutProjectSlice,
      AboutProjectSliceDefaultPrimary,
      AboutProjectSliceVariation,
      AboutProjectSliceDefault,
      AboutTextSlice,
      AboutTextSliceDefaultPrimary,
      AboutTextSliceVariation,
      AboutTextSliceDefault,
      CardProjectSlice,
      CardProjectSliceDefaultPrimary,
      CardProjectSliceVariation,
      CardProjectSliceDefault,
      DiptychImagesSlice,
      DiptychImagesSliceDefaultPrimarySideLeftItem,
      DiptychImagesSliceDefaultPrimarySideRightItem,
      DiptychImagesSliceDefaultPrimary,
      DiptychImagesSliceVariation,
      DiptychImagesSliceDefault,
      ProjectGroupSlice,
      ProjectGroupSliceDefaultPrimaryProjectsItem,
      ProjectGroupSliceDefaultPrimary,
      ProjectGroupSliceVariation,
      ProjectGroupSliceDefault,
      VariationsImagesSlice,
      VariationsImagesSliceDefaultPrimary,
      VariationsImagesSliceVariation,
      VariationsImagesSliceDefault,
    };
  }
}
